application: graphui-web
version: 1
runtime: python
api_version: 1
default_expiration: "7d"
handlers:
- url: /images
  static_dir: images
- url: /styles
  static_dir: styles
- url: /static
  static_dir: static
- url: /static/war
  static_files: static/war/Ui.html
  upload: static/war/Ui.html
